# Generated by Django 3.2.4 on 2021-06-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='sname',
            new_name='stores_name',
        ),
    ]
