# Generated by Django 3.2.4 on 2021-06-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0002_rename_sname_stores_stores_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='cfid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Stores.stores'),
            preserve_default=False,
        ),
    ]
