# Generated by Django 3.2.4 on 2021-06-24 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0003_coupon_cfid'),
    ]

    operations = [
        migrations.CreateModel(
            name='storecoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stores.coupon')),
                ('sfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stores.stores')),
            ],
        ),
    ]
