# Generated by Django 3.2.4 on 2021-06-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0008_alter_stores_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
