# Generated by Django 3.2.4 on 2021-06-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0009_alter_coupon_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stores',
            options={'ordering': ('-stores_name',)},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
