# Generated by Django 3.2.4 on 2021-06-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0010_auto_20210629_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='userview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewcount', models.TextField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='storecoupons',
        ),
    ]
