# Generated by Django 3.2.4 on 2021-06-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0011_auto_20210630_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userview',
            name='viewcount',
        ),
        migrations.AddField(
            model_name='stores',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='stores_count', to='Stores.userview'),
        ),
        migrations.AddField(
            model_name='userview',
            name='IP',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
