# Generated by Django 3.2.4 on 2021-06-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0012_auto_20210630_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userview',
            old_name='IP',
            new_name='ip',
        ),
    ]
