# Generated by Django 3.2.4 on 2021-06-23 10:53

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_percentage', models.IntegerField()),
                ('c_category', models.CharField(max_length=200)),
                ('c_credatetime', models.DateTimeField()),
                ('c_expdatetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='stores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stores_name', models.CharField(max_length=50)),
                ('stores_desc', models.CharField(default='', max_length=100)),
                ('stores_image', models.ImageField(default='', upload_to='Store/images/stores')),
                ('post_image', django_resized.forms.ResizedImageField(crop=None, default='', force_format=None, keep_meta=True, quality=0, size=[370, 250], upload_to='Store/images/stores')),
                ('stores_category', models.CharField(default='', max_length=100)),
                ('stores_subcategory', models.CharField(default='', max_length=100)),
                ('stores_datetime', models.DateTimeField()),
            ],
        ),
    ]
