# Generated by Django 3.2.4 on 2021-06-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='c_credatetime',
            new_name='ccredatetime',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='c_name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='c_percentage',
            new_name='cpercentage',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='stores_category',
            new_name='scategory',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='stores_datetime',
            new_name='sdatetime',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='stores_desc',
            new_name='sdesc',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='stores_image',
            new_name='simage',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='stores_name',
            new_name='sname',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='post_image',
            new_name='sresimage',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='stores_subcategory',
            new_name='ssubcategory',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='c_expdatetime',
        ),
        migrations.AddField(
            model_name='coupon',
            name='cexpdatetime',
            field=models.DateTimeField(default=''),
        ),
    ]
