# Generated by Django 3.2.4 on 2021-06-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0002_auto_20210623_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='cexpdatetime',
        ),
    ]
