# Generated by Django 3.2.4 on 2021-06-23 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0003_remove_coupon_cexpdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='cexpdatetime',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='ccredatetime',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
