# Generated by Django 3.2.4 on 2021-06-23 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0004_auto_20210623_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='ccredatetime',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='cexpdatetime',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
