# Generated by Django 3.2.4 on 2021-06-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0006_auto_20210623_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='ccredatetime',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='cexpdatetime',
        ),
        migrations.AddField(
            model_name='coupon',
            name='ccrdatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='cexdatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
