# Generated by Django 3.2.4 on 2021-06-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0007_auto_20210623_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='ccrdatetime',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='cexdatetime',
        ),
    ]
