# Generated by Django 3.2.5 on 2021-07-30 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stores', '0007_alter_offers_ourl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('bpercentage', models.IntegerField()),
                ('bcategory', models.CharField(max_length=200)),
                ('buses', models.IntegerField(default=0)),
                ('bdesc', models.CharField(max_length=300)),
                ('burl', models.CharField(blank=True, max_length=500)),
                ('bimage', models.ImageField(default='', upload_to='Home/images/banners/')),
                ('bfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stores.stores')),
            ],
        ),
    ]
