# Generated by Django 3.2.5 on 2021-07-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='bimage',
            field=models.ImageField(default='', upload_to='Home/'),
        ),
    ]
