# Generated by Django 3.2.4 on 2021-08-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('dprofession', models.CharField(max_length=50)),
                ('dlinkedin', models.URLField(max_length=100)),
                ('dcontact', models.IntegerField()),
                ('dphoto', models.ImageField(default='', upload_to='about/images/dphoto')),
            ],
        ),
        migrations.CreateModel(
            name='webinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waboutus', models.CharField(max_length=500)),
                ('wtitle', models.CharField(max_length=100)),
                ('wlogo', models.ImageField(default='', upload_to='about/images/logo')),
                ('wemail', models.TextField(max_length=199)),
            ],
        ),
    ]
