# Generated by Django 3.2.4 on 2021-07-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0002_alter_stores_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='stores',
            name='viewcount',
            field=models.ManyToManyField(blank=True, related_name='stores_views', to='Stores.IPmodel'),
        ),
    ]
