# Generated by Django 3.2.4 on 2021-07-15 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0004_coupon_ccrdatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=100)),
                ('opercentage', models.IntegerField()),
                ('ocategory', models.CharField(max_length=200)),
                ('uses', models.IntegerField(max_length=100)),
                ('odesc', models.CharField(max_length=300)),
                ('ourl', models.CharField(max_length=500)),
                ('oimage', models.ImageField(blank=True, default='', upload_to='Store/images/stores/offers')),
                ('ofid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stores.stores')),
            ],
        ),
    ]
