# Generated by Django 3.2.4 on 2021-07-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0005_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='uses',
        ),
        migrations.AddField(
            model_name='offers',
            name='ouses',
            field=models.IntegerField(default=0),
        ),
    ]
