# Generated by Django 3.2.4 on 2021-07-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0006_auto_20210715_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='ourl',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
