# Generated by Django 3.2.5 on 2021-08-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0008_alter_ipmodel_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='cdetails',
            field=models.CharField(default='', max_length=200),
        ),
    ]
