# Generated by Django 3.2.5 on 2021-08-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0010_coupon_cverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='cverify',
            field=models.BooleanField(default=True),
        ),
    ]
