# Generated by Django 3.2.5 on 2021-08-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0011_alter_coupon_cverify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='cverify',
        ),
        migrations.AddField(
            model_name='coupon',
            name='cverifed',
            field=models.BooleanField(default=True),
        ),
    ]
