# Generated by Django 3.2.5 on 2021-08-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0012_auto_20210804_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='cverifed',
        ),
    ]
