# Generated by Django 3.2.4 on 2021-08-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0014_coupon_cverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='ccode',
            field=models.CharField(default='abcd', max_length=100),
        ),
    ]
